version: '3.8'
services:
  cassandra:
    image: bitnami/cassandra:3.11.9
    volumes:
      - ./tmp/cassandra:/bitnami
    ports:
      - 127.0.0.1:9042:9042
    environment:
      CASSANDRA_USER: $CASSANDRA_USER
      CASSANDRA_PASSWORD: $CASSANDRA_PASSWORD
      CASSANDRA_CQL_PORT_NUMBER: $CASSANDRA_CQL_PORT_NUMBER
